### ISSUE TITLE
Getting errors while installing via npm

### ISSUE THREAD

**Issue by zafar-saleem** [clebert/r-pi-usonic#11]
I am getting following errors while install ultrasonic module via npm. Below is the output.
`npm WARN deprecated r-pi-usonic@2.5.0: THIS PROJECT IS NO LONGER MAINTAINED by clebert`
`npm WARN deprecated r-pi-gpio@3.0.0: THIS PROJECT IS NO LONGER MAINTAINED by clebert`

`> r-pi-gpio@3.0.0 install /home/pi/projects/usonicsensor/node_modules/r-pi-gpio`
`> node-gyp configure build`

`gyp WARN EACCES user "root" does not have permission to access the dev dir "/root/.node-gyp/8.3.0"`
`gyp WARN EACCES attempting to reinstall using temporary dev dir`
`"/home/pi/projects/usonicsensor/node_modules/r-pi-gpio/.node-gyp"`
`make: Entering directory '/home/pi/projects/usonicsensor/node_modules/r-pi-gpio/build'`
  `CXX(target) Release/obj.target/gpio/src/gpio.o`
  `CXX(target) Release/obj.target/gpio/src/node_gpio.o`
`In file included from ../../nan/nan.h:182:0,`
                 `from ../src/node_gpio.cc:2:`
`../../nan/nan_maybe_43_inl.h: In function 'Nan::MaybeLocal<v8::Object> `
Nan::CloneElementAt(v8::Local<v8::Array>, uint32_t)':
../../nan/nan_maybe_43_inl.h:221:58: warning: 'v8::MaybeLocal<v8::Object> v8::Array::CloneElementAt(v8::Local<v8::Context>, uint32_t)' is deprecated (declared at /home/pi/projects/usonicsensor/node_modules/r-pi-gpio/.node-gyp/8.3.0/include/node/v8.h:3457): Cloning is not supported. [-Wdeprecated-declarations]
   return array->CloneElementAt(GetCurrentContext(), index);
                                                          ^
In file included from ../../nan/nan_new.h:189:0,
                 from ../../nan/nan.h:188,
                 from ../src/node_gpio.cc:2:
../../nan/nan_implementation_12_inl.h: In static member function 'static Nan::imp::FactoryBase<v8::BooleanObject>::return_t Nan::imp::Factory<v8::BooleanObject>::New(bool)':
../../nan/nan_implementation_12_inl.h:40:38: warning: 'static v8::Local<v8::Value> v8::BooleanObject::New(bool)' is deprecated (declared at /home/pi/projects/usonicsensor/node_modules/r-pi-gpio/.node-gyp/8.3.0/include/node/v8.h:4749): Pass an isolate [-Wdeprecated-declarations]
   return v8::BooleanObject::New(value).As<v8::BooleanObject>();
                                      ^
In file included from ../src/node_gpio.cc:2:0:
../../nan/nan.h: At global scope:
../../nan/nan.h:590:20: error: variable or field 'AddGCEpilogueCallback' declared void
       v8::Isolate::GCEpilogueCallback callback
                    ^
../../nan/nan.h:590:7: error: 'GCEpilogueCallback' is not a member of 'v8::Isolate'
       v8::Isolate::GCEpilogueCallback callback
       ^
../../nan/nan.h:591:18: error: expected primary-expression before 'gc_type_filter'
     , v8::GCType gc_type_filter = v8::kGCTypeAll) {
                  ^
../../nan/nan.h:596:20: error: variable or field 'RemoveGCEpilogueCallback' declared void
       v8::Isolate::GCEpilogueCallback callback) {
                    ^
../../nan/nan.h:596:7: error: 'GCEpilogueCallback' is not a member of 'v8::Isolate'
       v8::Isolate::GCEpilogueCallback callback) {
       ^
../../nan/nan.h:601:20: error: variable or field 'AddGCPrologueCallback' declared void
       v8::Isolate::GCPrologueCallback callback
                    ^
../../nan/nan.h:601:7: error: 'GCPrologueCallback' is not a member of 'v8::Isolate'
       v8::Isolate::GCPrologueCallback callback
       ^
../../nan/nan.h:602:18: error: expected primary-expression before 'gc_type_filter'
     , v8::GCType gc_type_filter = v8::kGCTypeAll) {
                  ^
../../nan/nan.h:607:20: error: variable or field 'RemoveGCPrologueCallback' declared void
       v8::Isolate::GCPrologueCallback callback) {
                    ^
../../nan/nan.h:607:7: error: 'GCPrologueCallback' is not a member of 'v8::Isolate'
       v8::Isolate::GCPrologueCallback callback) {
       ^
../../nan/nan.h: In function 'bool Nan::SetAccessor(v8::Local<v8::Object>, v8::Local<v8::String>, Nan::GetterCallback, Nan::SetterCallback, v8::Local<v8::Value>, v8::AccessControl, v8::PropertyAttribute)':
../../nan/nan.h:1933:16: warning: 'bool v8::Object::SetAccessor(v8::Local<v8::Name>, v8::AccessorNameGetterCallback, v8::AccessorNameSetterCallback, v8::Local<v8::Value>, v8::AccessControl, v8::PropertyAttribute)' is deprecated (declared at /home/pi/projects/usonicsensor/node_modules/r-pi-gpio/.node-gyp/8.3.0/include/node/v8.h:3127): Use maybe version [-Wdeprecated-declarations]
     , attribute);
                ^
gpio.target.mk:94: recipe for target 'Release/obj.target/gpio/src/node_gpio.o' failed
make: *** [Release/obj.target/gpio/src/node_gpio.o] Error 1
make: Leaving directory '/home/pi/projects/usonicsensor/node_modules/r-pi-gpio/build'
gyp ERR! build error
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:258:23)
gyp ERR! stack     at emitTwo (events.js:125:13)
gyp ERR! stack     at ChildProcess.emit (events.js:213:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:200:12)
gyp ERR! System Linux 4.9.35-v7+
gyp ERR! command "/usr/bin/nodejs" "/usr/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "configure" "build"
gyp ERR! cwd /home/pi/projects/usonicsensor/node_modules/r-pi-gpio
gyp ERR! node -v v8.3.0
gyp ERR! node-gyp -v v3.6.2
gyp ERR! not ok
npm WARN usonicsensor@1.0.0 No description
npm WARN usonicsensor@1.0.0 No repository field.

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! r-pi-gpio@3.0.0 install: `node-gyp configure build`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the r-pi-gpio@3.0.0 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:`

**Comment by ahmetcanaksu** [comment]
use sudo npm install
